Repository opencast/opencast-editor, pull requests merged in 2022-03, with the labels that each got.

#547 Keyboard shortcut overview
  src/globalKeys.ts
  src/i18n/locales/en.json
  src/index.tsx
  src/main/CuttingActions.tsx
  src/main/KeyboardControls.tsx
  src/main/MainContent.tsx
  src/main/MainMenu.tsx
  src/types.ts
Labels: type:accessibility, type:usability

#642 Make Translations Work
  .crowdin.yaml
  .github/workflows/update-translations.yml
  crowdin.yml
  src/i18n/config.tsx
  src/i18n/locales/de-DE.json
  src/i18n/locales/en-US.json
  src/i18n/locales/es-ES.json
  src/i18n/locales/fr-FR.json
  src/i18n/locales/locales.json
  src/i18n/locales/nl-NL.json
  src/i18n/locales/pt.json
  src/i18n/locales/zh-CN.json
  src/i18n/locales/zh-TW.json
Labels: type:bug, type:usability

#643 Document Configuration Options
  README.md
Labels: type:documentation
