Repository opencast/opencast-editor, pull requests merged in 2022-06, with the labels that each got.

#444 Re-design of workflow selection
  src/main/WorkflowConfiguration.tsx
  src/main/WorkflowSelection.tsx
  src/redux/videoSlice.ts
Labels: type:visual-clarity, type:usability

#621 Made waveform always fill available height
  src/main/Timeline.tsx
Labels: type:usability

#718 Update release documentation
  README.md
Labels: type:documentation

#719 Ensure that the workflow id is set for single workflow
  src/main/WorkflowSelection.tsx
Labels: type:bug, priority:high

#650 Padding for long button labels
  src/main/FinishMenu.tsx
Labels: type:visual-clarity

#348 Display error if a workflow is running on the event
  src/i18n/locales/en-US.json
  src/main/Error.tsx
  src/main/Video.tsx
  src/redux/errorSlice.ts
  src/redux/metadataSlice.ts
  src/redux/videoSlice.ts
  src/redux/workflowPostAndProcessSlice.ts
  src/redux/workflowPostSlice.ts
  src/types.ts
Labels: type:usability
