Repository opencast/opencast-editor, pull requests merged in 2022-12, with the labels that each got.

#841 High contrast mode for subtitle editor
  src/cssStyles.tsx
  src/index.css
  src/main/MainContent.tsx
  src/main/Metadata.tsx
  src/main/SubtitleEditor.tsx
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleSelect.tsx
  src/main/SubtitleTimeline.tsx
  src/main/SubtitleVideoArea.tsx
  src/redux/themeSlice.ts
  src/themes.ts
Labels: type:accessibility

#836 Tooltips for subtitle editor
  src/i18n/locales/en-US.json
  src/main/SubtitleEditor.tsx
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleSelect.tsx
  src/main/SubtitleTimeline.tsx
  src/main/Tooltip.tsx
Labels: type:usability

#912 Start playback from beginning if at the end
  src/main/Video.tsx
Labels: type:enhancement

#911 Do not highlight timeline segments in thumbnail editor
  src/main/Thumbnail.tsx
  src/main/Timeline.tsx
Labels: type:visual-clarity

#909 Fix vertical scrolling
  src/main/Body.tsx
  src/main/MainContent.tsx
  src/main/MainMenu.tsx
Labels: type:visual-clarity, type:usability
