Repository opencast/opencast-editor, pull requests merged in 2022-10, with the labels that each got.

#795 Add workflow to check proper lable usage
  .github/workflows/check-label.yml
Labels: type:infrastructure

#796 change cursor style to text for react-select multi CreatableSelect
  src/cssStyles.tsx
Labels: type:usability

#794 Enable running the 'Update translations' workflow manually
  .github/workflows/update-translations.yml
Labels: type:infrastructure

#760 Thumbnail Editor
  public/editor-settings.toml
  src/config.ts
  src/cssStyles.tsx
  src/i18n/locales/en-US.json
  src/main/MainContent.tsx
  src/main/Thumbnail.tsx
  src/main/Timeline.tsx
  src/main/Video.tsx
  src/redux/videoSlice.ts
  src/types.ts
Labels: type:feature

#815 update readme section 'How to cat a release for Opencast'
  README.md
Labels: type:documentation, type:infrastructure

#816 add cleanup workflow
  .github/workflows/cleanup-deployments.yml
Labels: type:infrastructure

#638 SubtitleEditor
  package-lock.json
  package.json
  public/editor-settings.toml
  src/config.ts
  src/cssStyles.tsx
  src/globalKeys.ts
  src/i18n/locales/en-US.json
  src/main/CuttingActions.tsx
  src/main/FinishMenu.tsx
  src/main/KeyboardControls.tsx
  src/main/MainContent.tsx
  src/main/MainMenu.tsx
  src/main/Save.tsx
  src/main/Subtitle.tsx
  src/main/SubtitleEditor.tsx
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleSelect.tsx
  src/main/SubtitleTimeline.tsx
  src/main/SubtitleVideoArea.tsx
  src/main/Thumbnail.tsx
  src/main/Timeline.tsx
  src/main/TrackSelection.tsx
  src/main/Video.tsx
  src/main/WorkflowConfiguration.tsx
  src/redux/metadataSlice.ts
  src/redux/store.ts
  src/redux/subtitleSlice.ts
  src/redux/videoSlice.ts
  src/redux/workflowPostSlice.ts
  src/types.ts
  src/util/client.js
  src/util/utilityFunctions.ts
  src/util/webvtt-parser.d.ts
  tests/metadata.test.ts
Labels: type:feature, project:subtitle_editor

#759 Added high contrast mode
  src/cssStyles.tsx
  src/i18n/locales/de-DE.json
  src/i18n/locales/en-US.json
  src/index.css
  src/main/CuttingActions.tsx
  src/main/Discard.tsx
  src/main/Finish.tsx
  src/main/FinishMenu.tsx
  src/main/MainMenu.tsx
  src/main/Metadata.tsx
  src/main/Save.tsx
  src/main/SubtitleEditor.tsx
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleSelect.tsx
  src/main/TheEnd.tsx
  src/main/ThemeSwitcher.tsx
  src/main/Thumbnail.tsx
  src/main/Timeline.tsx
  src/main/TrackSelection.tsx
  src/main/Video.tsx
  src/main/WorkflowConfiguration.tsx
  src/redux/themeSlice.ts
  src/themes.ts
Labels: type:accessibility

#788 Improved tooltips
  src/i18n/locales/en-US.json
  src/main/CuttingActions.tsx
  src/main/Discard.tsx
  src/main/Metadata.tsx
  src/main/Save.tsx
  src/main/TheEnd.tsx
  src/main/Thumbnail.tsx
  src/main/Timeline.tsx
  src/main/Tooltip.tsx
  src/main/TrackSelection.tsx
  src/main/Video.tsx
  src/main/WorkflowConfiguration.tsx
  src/main/WorkflowSelection.tsx
  src/redux/themeSlice.ts
  src/themes.ts
Labels: type:visual-clarity, type:usability

#838 Remove superfluos "=" on landing page
  src/main/Landing.tsx
Labels: type:usability, small pull request

#828 Improve GHA
  .github/workflows/cleanup-deployments.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-crowdin-keys.yml
  .github/workflows/playwright-test.yml
  .github/workflows/update-test.yml
  .github/workflows/update-translations.yml
  .github/workflows/update.yml
Labels: type:infrastructure

#845 fix Test & Deploy workflow
  .github/workflows/update-test.yml
Labels: type:infrastructure

#829 Update Lockfile
  package-lock.json
Labels: type:dependencies

#844 Split demo and production configuration
  editor-settings.toml
  public/editor-settings.toml
Labels: type:documentation, type:infrastructure

#840 Update language strings
  src/i18n/locales/en-US.json
Labels: type:accessibility, type:usability

#848 fix Test & Deploy workflow
  .github/workflows/update-test.yml
Labels: type:infrastructure

#856 Test and deploy all organization member pull requests
  .github/workflows/update-test.yml
Labels: type:tests

#842 change text color for react-select multi CreatableSelect
  src/cssStyles.tsx
Labels: type:visual-clarity
