Repository opencast/opencast-editor, pull requests merged in 2022-11, with the labels that each got.

#878 Fix Dependabot test deployment
  .github/workflows/update-test.yml
Labels: type:infrastructure

#910 Add editor files to gitignore
  .gitignore
Labels: type:infrastructure

#886 Simplify code
  src/main/Subtitle.tsx
Labels: type:enhancement

#885 Show all existing subtitles
  src/i18n/locales/en-US.json
  src/main/SubtitleSelect.tsx
Labels: type:enhancement, view:subtitle-editor

#884 Thumbnail for video streams only
  src/main/Thumbnail.tsx
Labels: type:bug

#861 Remove broken cleanup workflow
  .github/workflows/cleanup-deployments.yml
Labels: type:infrastructure

#860 Icon Configuration for Languages
  editor-settings.toml
  public/editor-settings.toml
  src/config.ts
  src/main/SubtitleSelect.tsx
Labels: type:visual-clarity, type:usability

#855 Add aria-label to theme selector
  src/i18n/locales/en-US.json
  src/main/ThemeSwitcher.tsx
Labels: type:accessibility

#854 Replace scrubber language strings
  src/i18n/locales/en-US.json
Labels: type:usability

#849 Keep Playwright Test Results
  .github/workflows/playwright-test.yml
  playwright.config.ts
Labels: type:tests
