Repository opencast/opencast-editor, pull requests merged in 2022-07, with the labels that each got.

#736 Avoid calling dispatch on every rerender
  src/main/WorkflowConfiguration.tsx
  src/main/WorkflowSelection.tsx
Labels: type:enhancement, priority:high

#738 Update Typescript to 4.7.4
  package-lock.json
  package.json
  src/redux/videoSlice.ts
Labels: type:dependencies

#720 Added Darkmode
  src/App.tsx
  src/cssStyles.tsx
  src/i18n/locales/de-DE.json
  src/i18n/locales/en-US.json
  src/index.css
  src/main/CuttingActions.tsx
  src/main/Discard.tsx
  src/main/Finish.tsx
  src/main/FinishMenu.tsx
  src/main/KeyboardControls.tsx
  src/main/MainContent.tsx
  src/main/MainMenu.tsx
  src/main/Metadata.tsx
  src/main/Save.tsx
  src/main/TheEnd.tsx
  src/main/ThemeSwitcher.tsx
  src/main/Timeline.tsx
  src/main/TrackSelection.tsx
  src/main/Video.tsx
  src/main/WorkflowConfiguration.tsx
  src/main/WorkflowSelection.tsx
  src/redux/store.ts
  src/redux/themeSlice.ts
  src/themes.ts
  tests/metadata.test.ts
Labels: type:accessibility, type:feature
