Repository opencast/opencast-editor, pull requests merged in 2023-04, with the labels that each got.

#974 Add internal identifier for subtitle cues
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleTimeline.tsx
  src/redux/subtitleSlice.ts
  src/types.ts
  src/util/utilityFunctions.ts
Labels: type:usability, view:subtitle-editor

#1012 Add ICLA Check
  .github/workflows/check-icla.yml
Labels: type:infrastructure

#1010 Load locally if possible
  editor-settings.toml
  src/config.ts
  src/redux/videoSlice.ts
Labels: type:bug, type:enhancement

#979 Additional Hotkey to play back video in the subtitle editor
  src/globalKeys.ts
  src/main/KeyboardControls.tsx
Labels: type:enhancement, type:usability

#1030 Update reduxjs/toolkit to 1.9.3
  package-lock.json
  package.json
  src/main/Metadata.tsx
  src/redux/metadataSlice.ts
Labels: type:dependencies

#1028 No Workflow Error
  src/i18n/locales/en-US.json
  src/main/WorkflowSelection.tsx
Labels: type:bug

#1035 Make Studio and Editor look alike
  public/opencast-editor.svg
  src/App.tsx
  src/main/Body.tsx
  src/main/Header.tsx
  src/main/Timeline.tsx
Labels: type:visual-clarity

#895 Fix segment list unique key warning
  src/main/Timeline.tsx
Labels: type:bug

#1034 Display "Unsaved changes" for subtitles
  src/main/MainContent.tsx
  src/main/Save.tsx
  src/redux/subtitleSlice.ts
Labels: type:bug
