Repository opencast/opencast-editor, pull requests merged in 2023-07, with the labels that each got.

#1096 Convert text to path in logo
  public/opencast-editor.svg
Labels: type:visual-clarity

#1099 Add infos on waveform to ReadMe
  README.md
Labels: type:documentation

#1098 Combine "Configuration" sections in ReadMe
  README.md
Labels: type:documentation

#1082 Update react-virtualized-auto-resizer to 1.0.20
  package-lock.json
  package.json
  src/main/SubtitleListEditor.tsx
Labels: type:dependencies
