Repository opencast/opencast-editor, pull requests merged in 2023-09, with the labels that each got.

#1079 Redesign
  editor-settings.toml
  package-lock.json
  package.json
  public/editor-settings.toml
  src/App.tsx
  src/config.ts
  src/cssStyles.tsx
  src/i18n/locales/en-US.json
  src/img/opencast-editor.svg
  src/img/subtitle.svg
  src/img/trash-restore.svg
  src/index.css
  src/index.tsx
  src/main/Body.tsx
  src/main/Cutting.tsx
  src/main/CuttingActions.tsx
  src/main/Discard.tsx
  src/main/Error.tsx
  src/main/Finish.tsx
  src/main/FinishMenu.tsx
  src/main/Header.tsx
  src/main/KeyboardControls.tsx
  src/main/MainContent.tsx
  src/main/MainMenu.tsx
  src/main/Metadata.tsx
  src/main/Save.tsx
  src/main/SubtitleEditor.tsx
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleSelect.tsx
  src/main/SubtitleTimeline.tsx
  src/main/SubtitleVideoArea.tsx
  src/main/TheEnd.tsx
  src/main/ThemeSwitcher.tsx
  src/main/Thumbnail.tsx
  src/main/Timeline.tsx
  src/main/Tooltip.tsx
  src/main/TrackSelection.tsx
  src/main/Video.tsx
  src/main/VideoControls.tsx
  src/main/VideoPlayers.tsx
  src/main/WorkflowConfiguration.tsx
  src/main/WorkflowSelection.tsx
  src/redux/errorSlice.ts
  src/redux/store.ts
  src/redux/themeSlice.ts
  src/themes.ts
  src/util/appkit.ts
  tests/metadata.test.ts
Labels: type:enhancement, type:visual-clarity

#1097 Remove all segments button
  src/i18n/locales/en-US.json
  src/main/CuttingActions.tsx
  src/redux/videoSlice.ts
Labels: type:feature

#1100 Add callback url for integration (#1084)
  README.md
  editor-settings.toml
  public/editor-settings.toml
  src/config.ts
  src/i18n/locales/de-DE.json
  src/i18n/locales/en-US.json
  src/main/Finish.tsx
  src/main/Save.tsx
  src/main/TheEnd.tsx
Labels: type:feature

#1057 Update to react 18 rendering pipeline
  package-lock.json
  package.json
  src/config.ts
  src/globalKeys.ts
  src/index.tsx
  src/main/Body.tsx
  src/main/CuttingActions.tsx
  src/main/KeyboardControls.tsx
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleTimeline.tsx
  src/main/Timeline.tsx
  src/main/VideoControls.tsx
  src/main/VideoPlayers.tsx
  src/redux/videoSlice.ts
Labels: type:dependencies

#1139 Update typescript from 4 to 5
  package-lock.json
  package.json
Labels: type:dependencies

#1159 Bump appkit version for high contrast borders
  package-lock.json
  package.json
Labels: type:dependencies, type:visual-clarity, type:usability
