Repository opencast/opencast-editor, pull requests merged in 2023-10, with the labels that each got.

#1060 Add volume control
  src/i18n/locales/de-DE.json
  src/i18n/locales/en-US.json
  src/main/Cutting.tsx
  src/main/SubtitleVideoArea.tsx
  src/main/Thumbnail.tsx
  src/main/VideoControls.tsx
  src/main/VideoPlayers.tsx
  src/redux/videoSlice.ts
  src/themes.ts
Labels: type:feature

#1102 Implement editor locking so only one person can edit a recording a time
  .github/mock/editor/ID-dual-stream-demo/edit.json
  src/main/Body.tsx
  src/main/Lock.tsx
  src/redux/videoSlice.ts
  src/util/client.js
  src/util/utilityFunctions.ts
Labels: type:feature

#1179 fix #997, correct workflow ordering
  src/main/WorkflowSelection.tsx
  src/redux/videoSlice.ts
Labels: type:enhancement, type:usability

#1187 Fix #1186, incorrect color of btn icons on hover
  src/cssStyles.tsx
  src/main/CuttingActions.tsx
  src/main/TrackSelection.tsx
Labels: type:accessibility

#1185 Download subtitle files
  src/i18n/locales/cs-CZ.json
  src/i18n/locales/de-DE.json
  src/i18n/locales/el-GR.json
  src/i18n/locales/en-US.json
  src/i18n/locales/es-ES.json
  src/i18n/locales/fr-FR.json
  src/i18n/locales/nl-NL.json
  src/i18n/locales/zh-CN.json
  src/i18n/locales/zh-TW.json
  src/main/SubtitleEditor.tsx
Labels: type:feature
