Repository opencast/opencast-editor, pull requests merged in 2023-06, with the labels that each got.

#1053 Updated tests that were failing
  src/redux/__tests__/videoSlice.test.ts
Labels: type:tests

#329 Display critical error if Opencast does not provide a video duration
  src/i18n/locales/en-US.json
  src/main/Video.tsx
  src/redux/errorSlice.ts
  src/redux/videoSlice.ts
Labels: type:usability, small pull request

#908 Keep video controls row from overflowing to the left
  src/main/SubtitleSelect.tsx
  src/main/Video.tsx
Labels: type:visual-clarity

#1056 Update to React 18
  package-lock.json
  package.json
  src/main/KeyboardControls.tsx
  src/main/Metadata.tsx
  src/main/SubtitleSelect.tsx
  src/main/SubtitleTimeline.tsx
  src/main/SubtitleVideoArea.tsx
  src/main/WorkflowSelection.tsx
Labels: type:dependencies

#1058 Update to Node 18
  .github/workflows/create-release.yml
  .github/workflows/playwright-test.yml
  .github/workflows/update-test.yml
  .github/workflows/update.yml
Labels: type:infrastructure
