Repository opencast/opencast-editor, pull requests merged in 2024-12, with the labels that each got.

#1472 Unify save requests
  src/main/MainMenu.tsx
  src/main/Metadata.tsx
  src/main/Save.tsx
  src/main/WorkflowConfiguration.tsx
  src/redux/metadataSlice.ts
  src/redux/workflowPostAndProcessSlice.ts
  src/redux/workflowPostSlice.ts
  src/types.ts
Labels: type:code-quality

#1417 Fix random typing issues
  src/main/TrackSelection.tsx
  src/redux/videoSlice.ts
Labels: type:code-quality

#1416 Remove CRA ts definition file
  src/react-app-env.d.ts
Labels: type:code-quality

#1413 Remove duplicate save code
  src/main/Discard.tsx
  src/main/Finish.tsx
  src/main/Save.tsx
  src/main/WorkflowConfiguration.tsx
  src/main/WorkflowSelection.tsx
  src/redux/store.ts
  src/redux/workflowPostAndProcessSlice.ts
  src/redux/workflowPostSlice.ts
  src/types.ts
Labels: type:code-quality

#1495 Make behavior of forward button more intuitive
  src/redux/videoSlice.ts
Labels: type:usability

#1160 More small screen responsiveness
  src/cssStyles.tsx
  src/img/opencast-editor-narrow.svg
  src/main/CuttingActions.tsx
  src/main/Header.tsx
  src/main/MainMenu.tsx
  src/main/Metadata.tsx
  src/main/VideoControls.tsx
  src/util/utilityFunctions.ts
Labels: type:visual-clarity, type:usability

#1511 Add subtitle delete button
  src/i18n/locales/en-US.json
  src/main/Save.tsx
  src/main/SubtitleEditor.tsx
  src/main/SubtitleSelect.tsx
  src/redux/subtitleSlice.ts
  src/types.ts
Labels: type:enhancement, type:feature

#1393 Make use of ProtoButton from appkit
  src/cssStyles.tsx
  src/main/CuttingActions.tsx
  src/main/Discard.tsx
  src/main/Finish.tsx
  src/main/FinishMenu.tsx
  src/main/Header.tsx
  src/main/MainMenu.tsx
  src/main/Save.tsx
  src/main/SubtitleEditor.tsx
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleSelect.tsx
  src/main/TheEnd.tsx
  src/main/Thumbnail.tsx
  src/main/TrackSelection.tsx
  src/main/VideoControls.tsx
  tests/metadata.test.ts
  tests/navigation.test.ts
Labels: type:code-quality

#1390 Replace our spinner with appkits spinner
  src/cssStyles.tsx
  src/main/Save.tsx
  src/main/Timeline.tsx
  src/main/WorkflowConfiguration.tsx
Labels: type:visual-clarity

#1518 Update vite to major version 6
  package-lock.json
  package.json
Labels: type:dependencies

#1392 Make use of error boxes from appkit
  src/cssStyles.tsx
  src/main/Metadata.tsx
  src/main/Save.tsx
  src/main/VideoPlayers.tsx
  src/main/WorkflowConfiguration.tsx
  src/main/WorkflowSelection.tsx
Labels: type:visual-clarity
