Repository opencast/opencast-editor, pull requests merged in 2024-05, with the labels that each got.

#1311 Change wordings in finish menu
  src/i18n/locales/en-US.json
  src/main/WorkflowSelection.tsx
Labels: type:usability, discuss in dev meeting

#1318 Add context menu for cutting actions
  src/i18n/locales/en-US.json
  src/main/ContextMenu.tsx
  src/main/CuttingActionsContextMenu.tsx
  src/main/Timeline.tsx
  src/themes.ts
Labels: type:usability

#1317 Controls to jump to next or previous segment
  src/globalKeys.ts
  src/i18n/locales/de-DE.json
  src/i18n/locales/en-US.json
  src/main/Cutting.tsx
  src/main/SubtitleVideoArea.tsx
  src/main/Thumbnail.tsx
  src/main/VideoControls.tsx
  src/main/VideoPlayers.tsx
  src/redux/videoSlice.ts
Labels: type:feature

#1315 Movable cut marks
  src/i18n/locales/de-DE.json
  src/i18n/locales/en-US.json
  src/main/Timeline.tsx
  src/redux/videoSlice.ts
  src/themes.ts
Labels: type:feature

#1329 Dynamic skip threshold
  src/redux/videoSlice.ts
Labels: type:enhancement

#1331 Fix releaste note configuration
  .github/release.yml
Labels: type:infrastructure

#1332 Link subtitle tag documentation
  editor-settings.toml
Labels: type:documentation

#1330 Update to Node.js 20 (current LTS)
  .github/workflows/create-release.yml
  .github/workflows/playwright-test.yml
  .github/workflows/update-test.yml
  .github/workflows/update.yml
Labels: type:dependencies, type:tests

#1335 Document and link translation rules
  README.md
Labels: type:documentation

#1342 Dependabot configuration for GitHub Actions
  .github/dependabot.yml
Labels: type:infrastructure

#1341 Specify version of comment action
  .github/workflows/update-test.yml
Labels: type:infrastructure
