Repository opencast/opencast-editor, pull requests merged in 2024-04, with the labels that each got.

#1298 Replace REACT_ environment variables
  .github/build-release.sh
  index.html
  src/config.ts
  vite.config.ts
Labels: type:bug

#1297 Set vite base
  .github/mock/editor/ID-dual-stream-demo/metadata.json
  .gitignore
  src/config.ts
  src/i18n/config.tsx
  src/i18n/locales.json
  src/i18n/locales/locales.json
  tests/metadata.test.ts
  vite.config.ts
Labels: type:bug

#1260 Enforce eslint no-explicit-any
  .eslintrc.js
  src/config.ts
  src/cssStyles.tsx
  src/import-png.d.ts
  src/main/Metadata.tsx
  src/main/SubtitleSelect.tsx
  src/main/Thumbnail.tsx
  src/main/Timeline.tsx
  src/main/VideoPlayers.tsx
  src/redux/metadataSlice.ts
  src/redux/subtitleSlice.ts
  src/redux/videoSlice.ts
Labels: type:code-quality

#1310 Add lazy loading of lang files
  .github/generate-lngs.sh
  .github/workflows/update-translations.yml
  package-lock.json
  package.json
  src/i18n/LazyLoadingPlugin.ts
  src/i18n/config.tsx
  src/i18n/i18next.d.ts
  src/i18n/lngs-generated.ts
  src/main/Header.tsx
Labels: type:bug

#684 Add Dockerfile
  .dockerignore
  Dockerfile
  README.md
Labels: type:infrastructure
