Repository opencast/opencast-editor, pull requests merged in 2024-06, with the labels that each got.

#1229 Add upload subtitle button
  package-lock.json
  package.json
  src/i18n/locales/en-US.json
  src/main/SubtitleEditor.tsx
  src/util/utilityFunctions.ts
Labels: type:enhancement

#1383 Fix aspect ratio video box size in Safari
  src/main/VideoPlayers.tsx
Labels: type:bug, type:visual-clarity

#1385 Some stylistic nitpicks
  src/main/VideoPlayers.tsx
Labels: type:code-quality

#1386 `npx update-browserslist-db@latest`
  package-lock.json
Labels: type:dependencies

#1387 Remove flex gap polyfill
  src/cssStyles.tsx
  src/main/Discard.tsx
  src/main/Error.tsx
  src/main/FinishMenu.tsx
  src/main/Header.tsx
  src/main/KeyboardControls.tsx
  src/main/MainContent.tsx
  src/main/MainMenu.tsx
  src/main/Save.tsx
  src/main/SubtitleEditor.tsx
  src/main/SubtitleListEditor.tsx
  src/main/SubtitleSelect.tsx
  src/main/SubtitleVideoArea.tsx
  src/main/TheEnd.tsx
  src/main/Thumbnail.tsx
  src/main/TrackSelection.tsx
  src/main/VideoControls.tsx
  src/main/VideoPlayers.tsx
  src/main/WorkflowConfiguration.tsx
  src/main/WorkflowSelection.tsx
  src/util/utilityFunctions.ts
Labels: type:code-quality

#1033 Basic zoom functionality for the cutting view
  src/globalKeys.ts
  src/i18n/locales/en-US.json
  src/main/CuttingActions.tsx
  src/main/KeyboardControls.tsx
  src/main/SubtitleTimeline.tsx
  src/main/Timeline.tsx
  src/redux/videoSlice.ts
Labels: type:feature
