Repository opencast/opencast-editor, pull requests merged in 2024-08, with the labels that each got.

#1316 Subtitle editor: Allow to change end time of segment in timeline by drag and drop
  src/main/SubtitleTimeline.tsx
Labels: type:enhancement

#1424 Fix opencast editor logo
  src/main/Header.tsx
Labels: type:bug

#1376 Fix editor not playing audio due to video order
  src/main/VideoPlayers.tsx
Labels: type:bug

#1441 Fix the release script for macOS
  .github/build-release.sh
Labels: type:infrastructure
