Repository opencast/opencast-editor, pull requests merged in 2024-10, with the labels that each got.

#1468 Fix ICLA Check
  .github/workflows/check-icla.yml
Labels: type:tests

#1422 npm audit fix
  package-lock.json
Labels: type:dependencies

#1421 Update dependency react-player
  package-lock.json
  package.json
Labels: type:dependencies

#1423 Replace iarna/toml with smol-toml
  package-lock.json
  package.json
  src/config.ts
Labels: type:dependencies

#1419 Complete replacing jest with vitest
  package-lock.json
  package.json
  src/setupTests.ts
  tsconfig.json
  vite.config.ts
Labels: type:infrastructure, type:code-quality
