Repository opencast/opencast-editor, pull requests merged in 2025-05, with the labels that each got.

#1582 Load waveform images locally if possible
  src/redux/videoSlice.ts
Labels: type:bug, type:enhancement

#1579 GHA Workflow cleanups
  .github/workflows/update-test.yml
  .github/workflows/update.yml
Labels: type:infrastructure, github_actions

#1584 Changing the image-rendering of waveform images
  src/main/Timeline.tsx
  src/main/TrackSelection.tsx
Labels: type:visual-clarity

#1589 Revert Track Selection PR 1230 for 17.x
  editor-settings.toml
  public/editor-settings.toml
  src/config.ts
  src/cssStyles.tsx
  src/i18n/locales/en-US.json
  src/img/placeholder-waveform.png
  src/img/placeholder_waveform.png
  src/main/Save.tsx
  src/main/TrackSelection.tsx
  src/main/WorkflowConfiguration.tsx
  src/redux/videoSlice.ts
  src/redux/workflowPostSlice.ts
  src/types.ts
  src/util/utilityFunctions.ts
Labels: type:enhancement

#1590 Re-Introduce Track Selection PR 1230 to develop
  editor-settings.toml
  public/editor-settings.toml
  src/config.ts
  src/cssStyles.tsx
  src/i18n/locales/en-US.json
  src/img/placeholder-waveform.png
  src/img/placeholder_waveform.png
  src/main/Save.tsx
  src/main/TrackSelection.tsx
  src/main/WorkflowConfiguration.tsx
  src/redux/videoSlice.ts
  src/redux/workflowPostSlice.ts
  src/types.ts
  src/util/utilityFunctions.ts
Labels: type:enhancement

#1209 Don't show track view if there is only one track
  editor-settings.toml
  src/i18n/locales/en-US.json
  src/main/TrackSelection.tsx
Labels: type:visual-clarity
